"""Rest overlay bilingual quotes (extracted from original)."""

REST_QUOTES = [
    ("Even a Ferrari needs a pit stop. You're a Ferrari, right?", '法拉利也需要进站加油。你也是法拉利，对吧？'),
    ("The computer won't run away. Promise.", '电脑不会长腿跑掉的，我保证。'),
    ('Time to blink manually.', '是时候手动眨眨眼了。'),
    ('Your spine called. It wants to be straight for a bit.', '你的脊椎打电话来了，它想稍微直一直。'),
    ('Hydrate or diedrate. Go drink water.', '要么喝水，要么枯萎。去喝水。'),
    ('404: Energy Not Found. Please reboot yourself.', '404：未找到能量。请重启你自己。'),
    ('Step away from the glowing rectangle.', '离那个发光的长方形远一点。'),
    ("You've been sitting longer than a gargoyle.", '你坐得比石像鬼还久。'),
    ("Reality is calling. It's high resolution out there.", '现实在呼唤。外面的分辨率很高的。'),
    ("Give your mouse a break. It's exhausted.", '放过你的鼠标吧，它累坏了。'),
    ('Look at something further than 50cm away. Like a wall.', '看点50厘米以外的东西。比如墙。'),
    ("If you don't rest, your bugs will multiply.", '如果你不休息，你的Bug会繁殖的。'),
    ("Stretch. You don't want to turn into a shrimp.", '伸个懒腰。你不想变成一只虾米吧。'),
    ('Pause game. Life continues.', '游戏暂停。生活继续。'),
    ('Go annoy your cat/dog/colleague for a moment.', '去骚扰一下你的猫/狗/同事吧。'),
    ('Ctrl+Alt+Del your fatigue.', 'Ctrl+Alt+Del 强制结束你的疲劳。'),
    ("Loading 'Energy'... Please wait 30 seconds.", '正在加载“能量”... 请等待30秒。'),
    ('A rested brain is a sexy brain.', '休息过的大脑才是性感的大脑。'),
    ("Don't let the pixels hypnotize you.", '别让像素把你催眠了。'),
    ('Nature called. Not the bathroom, actual nature.', '大自然在召唤。不是指厕所，是真的大自然。'),
    ('Your chair misses your absence.', '你的椅子怀念你不在的时候。'),
    ('Refresh your soul, not just the webpage.', '刷新一下灵魂，而不只是网页。'),
    ('Keep calm and take a break.', '保持冷静，休息一下。'),
    ('System Overheat. Cooling required.', '系统过热。需要冷却。'),
    ('Battery Low. Please recharge with coffee or tea.', '电量低。请用咖啡或茶充电。'),
    ("Remember the sun? It's that bright ball in the sky.", '还记得太阳吗？就是天上那个亮球。'),
    ('Typing speed -50% due to fatigue.', '由于疲劳，打字速度 -50%。'),
    ('AFK (Away From Keyboard) for a bit.', '暂时 AFK 一下吧。'),
    ('You are not a robot. Or are you?', '你不是机器人。还是说你是？'),
    ('Your brain has left the chat. Please wait for it to reconnect.', '你的大脑已退出群聊。请等待重连。'),
    ('Error 404: Motivation not found. Reboot required.', '错误 404：未找到动力。需要重启。'),
    ('Stop typing. The keyboard is filing a restraining order.', '别敲了。键盘正在申请针对你的限制令。'),
    ('Go look at a tree. A real one. Not a decision tree.', '去看棵树。真的树。不是决策树。'),
    ('You are simulating a statue perfectly. Now move.', '你模仿雕像模仿得很完美。现在动一下。'),
    ('Your posture resembles a cooked shrimp. Straighten up.', '你的坐姿像只煮熟的虾米。直起来。'),
    ('Even the CPU throttles when it gets too hot. Chill.', 'CPU 热了都知道降频。你也冷静下。'),
    ('Your eyes are dry. Blink. Like a human.', '眼睛干了。眨眼。像个人类那样。'),
    ('Warning: User battery is critically low.', '警告：用户电量严重不足。'),
    ('I bet you forgot what the sun looks like.', '我打赌你忘了太阳长什么样了。'),
    ('Clear your cache. And by cache, I mean your head.', '清一下缓存。我是说你的脑子。'),
    ('Ctrl+S your work, Ctrl+Alt+Del your stress.', 'Ctrl+S 保存工作，Ctrl+Alt+Del 结束压力。'),
    ('Have you tried turning yourself off and on again?', '你试过把自己关机再重启吗？'),
    ('Your spine is plotting revenge against you.', '你的脊椎正在密谋报复你。'),
    ('The bugs will still be there in 5 minutes.', 'Bug 还是那个 Bug，5分钟后它还在那。'),
    ("Don't let the blue light turn you into a zombie.", '别让蓝光把你变成了僵尸。'),
    ('Touch grass. Literally.', '去摸摸草。字面意思。'),
    ('Stand up. Your butt is falling asleep.', '站起来。你的屁股睡着了。'),
    ('System maintenance required: Intake caffeine or water.', '需要系统维护：摄入咖啡因或水。'),
    ("You've been scroll-locked. Unlock yourself.", '你被 Scroll Lock 了。给自己解锁吧。'),
    ('Nature called. It left a voicemail. Go listen.', '大自然来电话了。留了语音信箱。去听听。'),
    ('Taking a break is part of the algorithm.', '休息也是算法的一部分。'),
    ("Don't code a memory leak in your own brain.", '别给自己脑子里写出内存泄漏了。'),
    ('Your lumbar support misses you. Lean back.', '你的腰靠想你了。往后靠靠。'),
    ('A 5-minute break saves 5 hours of debugging.', '休息5分钟，省下5小时改 Bug。'),
    ('Are you waiting for a segmentation fault in your body?', '你在等身体报段错误吗？'),
    ('Esc key is not just on the keyboard.', 'Esc 键不只在键盘上。'),
    ('Refresh your perspective, not just the browser.', '刷新一下视野，而不只是浏览器。'),
    ('Gravity check: Can you still stand up?', '重力检查：你还能站起来吗？'),
    ('The internet will survive without you for 5 minutes.', '没你这5分钟，互联网也不会崩。'),
    ('Your screen resolution is high. Your vision is getting low.', '屏幕分辨率挺高。你的视力在走低。'),
    ("Don't be a browser tab that plays music you can't find.", '别做那个找不到在哪放音乐的浏览器标签页。'),
    ('Stretch. Do not evolve into a T-Rex.', '伸展一下。别退化成霸王龙。'),
    ('Close your eyes. Visualize a beach. Or a bed.', '闭眼。想象海滩。或者一张床。'),
    ('Your RAM is full. Garbage collection needed.', '内存满了。需要进行垃圾回收。'),
    ('Step away from the machine, human.', '离开那台机器，人类。'),
    ('Loading fresh air... 0% complete.', '正在加载新鲜空气... 完成度 0%。'),
    ('Ping timeout. Your brain is lagging.', 'Ping 超时。你的大脑卡顿了。'),
    ('Look at something 20 feet away for 20 seconds.', '看20英尺外的东西20秒（20-20-20法则）。'),
    ("You are not a robot. Robots don't get back pain.", '你不是机器人。机器人不会腰疼。'),
    ("Don't let your coffee get cold while you stare at code.", '别盯着代码看，把咖啡放凉了。'),
    ('Minimize all windows. Maximize wellness.', '最小化所有窗口。最大化健康。'),
    ('Time for a bio-break. You know what that means.', '生物钟休息时间。你懂我意思。'),
    ('Checking connection to reality... Signal weak.', '正在检查与现实的连接... 信号微弱。'),
    ('Put the mouse down slowly and nobody gets hurt.', '慢慢放下鼠标，没人会受伤。'),
    ("Go annoy a coworker. It's social interaction.", '去打扰个同事。这也算社交。'),
    ('Take a deep breath. Not a shallow one. A deep one.', '深呼吸。不是浅呼吸。是深呼吸。'),
    ('Is your neck made of stone? Rotate it.', '脖子是石头做的吗？转一转。'),
    ('The matrix has you. Jack out for a bit.', '你被矩阵困住了。拔线出来一会儿。'),
    ("Don't doom-scroll. Doom-stretch instead.", '别刷屏了。起来“刷”个懒腰。'),
    ('Your typing speed is dropping. Your typos are rising.', '打字速度在降。错别字在涨。'),
    ('Give your eyes a holiday.', '给眼睛放个假。'),
    ('Remember blinking? It keeps eyes moist. Try it.', '还记得眨眼吗？能保湿。试试看。'),
    ('Go find a window. Look out of it.', '找个窗户。往外看。'),
    ('Hydrate. Your brain is 73% water. Refill it.', '补水。你脑子73%是水。续杯。'),
    ('Status update: User needs a reboot.', '状态更新：用户需要重启。'),
    ("Don't become a legacy system.", '别让自己成了“老旧系统”。'),
    ("Run diagnostic tool: 'Walk_Around_Room.exe'.", "运行诊断工具：'屋里走两步.exe'。"),
    ('There is no dark mode for real life fatigue.', '现实生活的疲劳可没有“深色模式”。'),
    ('Your code is compiling. You should be stretching.', '代码在编译。你应该在拉伸。'),
    ('Disconnect to reconnect.', '断开连接，为了更好地连接。'),
    ('Screen time is up. Real time begins.', '屏幕时间到。现实时间开始。'),
    ('Avoid burnout. It smells like toasted wires.', '避免过劳烧毁。闻起来像烤焦的电线。'),
    ('You have been idle in real life for too long.', '你在现实生活中“挂机”太久了。'),
    ('Go stretch your legs before they forget how to walk.', '去伸伸腿，趁它们还没忘怎么走路。'),
    ('Alert: Caffeine levels dropping. Cortisol rising.', '警报：咖啡因水平下降。皮质醇上升。'),
    ("Look up. The ceiling is boring, but it's not a screen.", '抬头。天花板很无聊，但它不是屏幕。'),
    ('Shake your hands out. Jazz hands!', '甩甩手。爵士手！'),
    ('Are your shoulders touching your ears? Drop them.', '肩膀缩到耳朵那儿了吗？放下来。'),
    ('Defag your mind.', '对你的大脑进行磁盘碎片整理。'),
    ("Force quit 'Worrying'.", '强制退出“焦虑”进程。'),
    ('Even superheroes take off the cape sometimes.', '超级英雄有时候也得脱下披风。'),
    ("Walk away. The solution will come when you're peeing.", '走开一会。上厕所的时候方案自然就有了。'),
    ('Save your game. Pause your work.', '保存游戏。暂停工作。'),
    ('Low power mode enabled for Human.', '人类低电量模式已启用。'),
    ('Detecting high stress levels. Abort mission immediately.', '检测到高压力水平。立即中止任务。'),
    ('You look like you need a hug. Or a nap.', '你看着像需要一个拥抱。或者一个午觉。'),
    ('Be right back. You, not the computer.', '马上回来（BRB）。是指你，不是电脑。'),
    ("Unlock achievement: 'Stood Up Today'.", '解锁成就：‘今天站起来过’。'),
    ("Don't let the pixels bite.", '别让像素咬你一口。'),
    ("Are you a mushroom? Because you're sitting in the dark.", '你是蘑菇吗？一直坐在黑影里。'),
    ('Give your biological neural network a rest.', '给你的生物神经网络放个假。'),
    ('Overheating warning. Vent heat by walking.', '过热警告。通过散步散热。'),
    ('Remember, you are carbon-based, not silicon-based.', '记住，你是碳基生物，不是硅基生物。'),
    ('Stop slouching. You look like a question mark.', '别驼背。你看着像个问号。'),
    ('Go make some tea. The ritual is healing.', '去泡杯茶。这个仪式很治愈。'),
    ("Close tab: 'Stress'. Open tab: 'Peace'.", '关闭标签页：‘压力’。打开标签页：‘平静’。'),
    ('Your output quality is degrading. Rest required.', '产出质量在下降。要求休息。'),
    ("Don't ignore the hardware (your body).", '别忽视了硬件（你的身体）。'),
    ('Keep calm and step away from the keyboard.', '保持冷静，远离键盘。'),
    ("Life is not a sprint. It's a marathon with snack breaks.", '生活不是冲刺。是有零食时间的马拉松。'),
    ('Go get some Vitamin D. The real kind.', '去搞点维他命D。真的那种。'),
    ("Even the internet sleeps... wait, no it doesn't. But you should.", '互联网都睡觉... 呃它不睡。但你应该睡。'),
    ('Reset your uptime.', '重置你的运行时间。'),
    ('Switch off to switch on.', '关机是为了更好地开机。'),
    ('Your focus needs autofocusing.', '你的注意力需要自动对焦了。'),
    ("Don't let your dreams be dreams. But do sleep.", '别让梦想只是梦想。但觉还是要睡的。'),
]
